name: Keep Actions Alive

on:
  schedule:
    # раз в неделю по понедельникам 07:00 UTC
    - cron: "0 7 * * 1"
  workflow_dispatch:

# нужно, чтобы экшн мог сделать коммит в репозиторий
permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      # Готовый экшн. Если с последнего коммита прошло >= 45 дней — сделает небольшой коммит.
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: "chore: keepalive"
          # через сколько дней без активности делать коммит
          time_elapsed: 45
