name: WB Paid Storage Daily Sync

on:
  schedule:
    # Ежедневно в 07:05 по Europe/Amsterdam.
    # ВАЖНО: cron в UTC. Летом AMS=UTC+2 → ставим 05:05 UTC.
    - cron: '5 5 * * *'
  workflow_dispatch: {}   # чтобы можно было запустить вручную

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests supabase==2.6.0
      - name: Daily sync (last 8 days)
  timeout-minutes: 40
  env:
    PYTHONUNBUFFERED: "1"
    WB_API_TOKEN: ${{ secrets.WB_API_TOKEN }}
    SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  run: python wb_paid_storage_sync.py sync 8

