name: WB Paid Storage Daily Sync

on:
  schedule:
    # Ежедневно 07:05 по Amsterdam (UTC+2 летом → 05:05 UTC)
    - cron: '5 5 * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # (опционально) общий таймаут для job

    steps:
      - uses: actions/checkout@v4

      # (опц.) проверка, что секреты реально подтянулись
      - name: Debug env
        run: |
          python - << 'PY'
          import os
          print("WB_TOKEN length:", len(os.environ.get("WB_API_TOKEN","")))
          print("SUPABASE_URL set:", bool(os.environ.get("SUPABASE_URL")))
          print("SERVICE_ROLE set:", bool(os.environ.get("SUPABASE_SERVICE_ROLE_KEY")))
          PY
        env:
          WB_API_TOKEN: ${{ secrets.WB_API_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests supabase==2.6.0

      - name: Daily sync (last 8 days)
        env:
          PYTHONUNBUFFERED: "1"  # чтобы логи печатались сразу
          WB_API_TOKEN: ${{ secrets.WB_API_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python wb_paid_storage_sync.py sync 8
        timeout-minutes: 40  # таймаут именно этого шага
