name: WB Paid Storage Sync

on:
  workflow_dispatch:
    inputs:
      days_back:
        description: "Сколько дней назад захватить (1..8)"
        required: false
        default: "8"
  schedule:
    # каждые 15 минут; можешь сократить/увеличить
    - cron: "*/15 * * * *"

concurrency:
  group: wb-paid-storage-sync
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install requests supabase==2.6.0

      - name: Sanity check env
        run: |
          python - <<'PY'
          import os
          for k in ("WB_API_TOKEN","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"):
              v=os.getenv(k)
              print(f"{k} set: {bool(v)}")
          PY
        env:
          WB_API_TOKEN: ${{ secrets.WB_API_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Sync last N days (<=8)
        env:
          WB_API_TOKEN: ${{ secrets.WB_API_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # при ручном запуске можно переопределить
          DAYS_BACK: ${{ inputs.days_back }}
        run: |
          python wb_paid_storage_sync.py sync "${DAYS_BACK:-8}"
